use raylib::prelude::*;

const MENU_GAP: f32 = 8.0;
const MENU_WIDTH: f32 = 400.0;
const MENU_ELEMENT_HEIGHT: f32 = 24.0;
const MENU_ELEMENT_FULLWIDTH: f32 = MENU_WIDTH - 2.0 * MENU_GAP;
const MENU_ELEMENT_FULLWIDTH_INSIDEGROUP: f32 = MENU_WIDTH - 4.0 * MENU_GAP;
const MENU_ELEMENT_HALFWIDTH: f32 = MENU_ELEMENT_FULLWIDTH / 2.0 - MENU_GAP / 2.0;
const MENU_ELEMENT_HALFWIDTH_INSIDEGROUP: f32 = MENU_ELEMENT_FULLWIDTH_INSIDEGROUP / 2.0 - MENU_GAP / 2.0;
const MENU_HEIGHT: f32 = MENU_ELEMENT_HEIGHT * 11.0 + 13.0 * MENU_GAP;

const HUD_GAP: f32 = 8.0;
const HUD_SQUARESIZE: f32 = 24.0;
const HUD_WIDTH: f32 = 13.0 * HUD_SQUARESIZE + 14.0 * HUD_GAP;
const HUD_HEIGHT: f32 = 3.0 * HUD_GAP + 2.0 * HUD_SQUARESIZE;
const HUD_BAR_WIDTH: f32 = 10.0 * HUD_SQUARESIZE + 9.0 * HUD_GAP;
const HUD_BAR_HEIGHT: f32 = HUD_GAP * 1.0;

